Traceback (most recent call last):
  File "/usr/share/miniconda/envs/swd8_intro_ml/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/swd8_intro_ml/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/swd8_intro_ml/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/swd8_intro_ml/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/swd8_intro_ml/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/swd8_intro_ml/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/swd8_intro_ml/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/swd8_intro_ml/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# train.py
def main(hparams):
    model = LightningTemplateModel(hparams)

    trainer = Trainer(accelerator="gpu", devices=8, num_nodes=4, strategy="ddp")

    trainer.fit(model)


if __name__ == "__main__":
    root_dir = os.path.dirname(os.path.realpath(__file__))
    parent_parser = ArgumentParser(add_help=False)
    hyperparams = parser.parse_args()

    # TRAIN
    main(hyperparams)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [24][0m, in [0;36m<cell line: 10>[0;34m()[0m
[1;32m      7[0m     trainer[38;5;241m.[39mfit(model)
[1;32m     10[0m [38;5;28;01mif[39;00m [38;5;18m__name__[39m [38;5;241m==[39m [38;5;124m"[39m[38;5;124m__main__[39m[38;5;124m"[39m:
[0;32m---> 11[0m     root_dir [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mdirname(os[38;5;241m.[39mpath[38;5;241m.[39mrealpath([38;5;18;43m__file__[39;49m))
[1;32m     12[0m     parent_parser [38;5;241m=[39m ArgumentParser(add_help[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[1;32m     13[0m     hyperparams [38;5;241m=[39m parser[38;5;241m.[39mparse_args()

[0;31mNameError[0m: name '__file__' is not defined
NameError: name '__file__' is not defined

